use crate::Rouille;

pub struct Italiano;

impl Rouille for Italiano {
    fn traduire(ident_str: &str) -> Option<&str> {
        Some(match ident_str {
            "Arf" => "Err",
            "Bene" => "Ok",
            "Catena" => "String",
            "Dizionario" => "HashMap",
            "Default" => "Default",
            "Errore" => "Error",
            "Forse" => "Option",
            "Alcuni" => "Some",
            "Niente" => "None",
            "Risultato" => "Result",
            "Sé" => "Self",
            "visualizza" => "println",
            "fermare" => "break",
            "asincrono" => "async",
            "attendere" => "await",
            "loop" => "loop",
            "spostare" => "move",
            "cassa" => "crate",
            "codice_inaccessibile" => "unreachable_code",
            "come" => "as",
            "costante" => "const",
            "convenzione" => "trait",
            "pericoloso" => "unsafe",
            "a" => "in",
            "da" => "from",
            "dinamico" => "dyn",
            "scartare" => "unwrap",
            "default" => "default",
            "come_rif" => "as_ref",
            "" => "io",
            "esterno" => "extern",
            "falso" => "false",
            "funzione" => "fn",
            "grande" => "super",
            "inserire" => "insert",
            "leggere" => "get",
            "legale" => "allow",
            "merda" | "calisse" | "oups" => "panic",
            "modulo" => "mod",
            "mutevole" => "mut",
            "nuovo" => "new",
            "dove" => "where",
            "per" => "for",
            "prendere_o_inserire_con" => "get_or_insert_with",
            "principale" => "main",
            "pubblico" => "pub",
            "che" => None?,
            "restituisce" => "return",
            "raggiungimento" => "impl",
            "rif" => "ref",
            "corrisponde" => "match",
            "se" => "if",
            "altrimenti" => "else",
            "auto" => "self",
            "lascia" => "let",
            "statico" => "static",
            "struttura" => "struct",
            "implica" => "expect",
            "entrambi" => "while",
            "utilizzare" => "use",
            "verso" => "into",
            "vero" => "true",
            "enumerazione" => "enum",
            "non_implementato" => "unimplemented",

            _ => ident_str,
        })
    }
}
